project:
  type: website
  output-dir: "docs"
  

website:
  title: "prueba_individual"
  navbar:
    left:
      - href: ana.qmd
        text: Ana
      - href: bruno.qmd
        text: Bruno        
      - about.qmd
      - href: https://aniuxa.github.io/renoe/
        text: Paquete  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

